### ISSUE TITLE
Does it work for fields which dont have defined regex

### ISSUE THREAD

**Issue by mon28** [Praneet9/Representation-Learning-for-Information-Extraction#22]
Hi,

Looks like a great implementation. I have a usecase to try this solution on, expect i was looking to extract more fields like company name, item description.
Would it work for fields we cant apply regex on?

**Comment by Praneet9** [comment]
Hi @mon28,
I think the neural network is built for such kind of fields where we can't use regex. You might need to set up your data accordingly though.

**Comment by mon28** [comment]
> You might need to set up your data accordingly though.

Can you elaborate more on this?
Also, what does it mean for the above-mentioned fields in extract_candidates.py? Does it mean it's ok to not have candidates for all fields?

**Comment by mon28** [comment]
Basically, you use regex to extract spatial location out of the tesseract string_to_data output of an image. If regex is not something that can be used for some labels like company_name, what is something else that can help me get what you get using get_candidates()

**Comment by mon28** [comment]
Oh, i already have the annotated xmls. I was confused why you weren't using them for the same

**Comment by mon28** [comment]
Yeah, so i won't be able to get negative candidates this if I use just my xmls too.

**Comment by mon28** [comment]
How important is it for the model to have negative candidates? 
And how much accuracy did this model present?

**Comment by Praneet9** [comment]
Yup! You can maybe a write a similar script to extract company name like text as your negative candidates. Assuming company name is always bold or bigger in size, you can use such rules to extract the negative candidates. Or you can just take random text for it too, which in my opinion isn't the best thing to do.

**Comment by Praneet9** [comment]
It's as important as having negative examples in your dataset along with the positive ones. We trained it for some dataset that we collected and it gave good recall of around 0.8 i guess.
