### ISSUE TITLE
Request to help in sorting out an error

### ISSUE THREAD

**Issue by imgarvit** [Praneet9/Representation-Learning-for-Information-Extraction#28]
Hi, I tried to clone the code and run on my local machine but I am facing this error when I try to run train.py. In ths file the following error is showing up:
ValueError: num_samples should be a positive integer value, but got num_samples=0 error .
In my train_data object only vocab has 512 words, everything else is blank. Is that how its supposed to be? The length of my training_data is 1. Can you help me out?

**Comment by Praneet9** [comment]
Can you check if your dataset is loaded properly? It seems your loaded data is empty. Make sure you have the right path for your dataset.
Please follow the readme for preparing data, you might have missed some points.
If it still doesn't work, please add a screenshot of the traceback and a bit more details on how your data is structured.

**Comment by imgarvit** [comment]
I took images of docs and used labelImg to get the xml files, the images and xmls folder have the reqd data, I have small dataset though (8 train, 2 validation), but that should not be an issue right? I think I have correclty done everything mentioned in the readme.

The error is in this line:
 training_data = data.DataLoader(train_data, batch_size=config.BATCH_SIZE, shuffle=True)

**Comment by CS-savvy** [comment]
Yes, your dataset is having very few items, after annotation, there is 3 more steps :
1. Generate OCR using tesseract.
2. Extract candidates using extract_candidates.py
3. Define your split and add detail in config.py
