### ISSUE TITLE
Inference.py

### ISSUE THREAD

**Issue by shahurvi84** [Praneet9/Representation-Learning-for-Information-Extraction#31]
Hi,

Thanks for the code.

I have two questions on inference.py.
1. What should be cached_data.pickle? Should it be cached_data_train.pickle or cached_data_val.pickle?
2. Model is saved with help of 5 parameters "field, candidate, words, positions, masks". However, inference is using only 4 parameters (field_ids, candidate_cords, neighbours, neighbour_cords). This is resulting in error while executing inference.py. Can you guide me if I am missing something?

Below is the error that I am getting.

forward() missing 1 required positional argument: 'masks'

Thanks in advance

**Comment by Praneet9** [comment]
1. It needs to be `cached_data_train.pickle`
2. You need to pass in masks=None for it as it is used for self-attention. It's an optional arg, so you can pass in `None` there and it should work
