### ISSUE TITLE
STEP 3: Extract Candidates.py

### ISSUE THREAD

**Issue by wijayawilly** [Praneet9/Representation-Learning-for-Information-Extraction#32]
can someone elaborate how to use extract_candidates.py ? 
i have done step1, and 2, but now i'm stuck at the step 3 on how to get the candidates ?

**Comment by Praneet9** [comment]
You will have to modify the script for your classes. We have already implemented it for `Invoice numbers`, `Amounts` and `Dates`. In case you have any other, you will have to write your own.
